#ansible-playbook -i /home/ubuntu/ansible/group_vars/inventory.yml --private-key=/home/ubuntu/.ssh/bastion.pem
#ansible myhosts -m ping -i /home/ubuntu/ansible/group_vars/inventory.yml

---
- name: Create VPC, Subnets and SG
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Create VPC
      community.aws.ec2_vpc_net:
        name: dw_VPC
        cidr_block: 10.11.0.0/16
        region: {{ region }}
      register: vpc_result

    - name: Public Subnets
      community.aws.ec2_vpc_net:
        vpc_id: "{{ vpc_result.vpc.id }}"
        cidr: "{{ item.cidr }}"
        az: "{{ item.az }}"
        region: {{ region }}
        map_public: true
      with_items:
        - { cidr: 10.11.1.0/24, az: "{{ region }}a" }
        - { cidr: 10.11.2.0/24, az: "{{ region }}b" }
      register: public_subnet_result

    - name: Private Subnets
      community.aws.ec2_vpc_net:
        vpc_id: "{{ vpc_result.vpc.id }}"
        cidr: "{{ item.cidr }}"
        az: "{{ item.az }}"
        region: {{ region }}
        map_public: false
      with_items:
        - { cidr: 10.11.3.0/24, az: "{{ region }}a" }
        - { cidr: 10.11.4.0/24, az: "{{ region }}b" }
      register: private_subnet_result

    - name: public-access-sg
      community.aws.ec2_vpc_net:
      ec2_group:
        name: public-access-sg
        description: Security group for instances in public subnets
        vpc_id: "{{ vpc_result.vpc.id }}"
        az: "{{ item.az }}"
        region: {{ region }}
      register: public_sg_result

    - name: private-access-sg
      community.aws.ec2_vpc_net:
      ec2_group:
        name: private-access-sg
        description: Security group for instances in public subnets
        vpc_id: "{{ vpc_result.vpc.id }}"
        az: "{{ item.az }}"
        region: {{ region }}
      register: private_sg_result

