#ansible-playbook -i /home/ubuntu/ansible/group_vars/inventory.yml --private-key=/home/ubuntu/.ssh/bastion.pem
#ansible myhosts -m ping -i /home/ubuntu/ansible/group_vars/inventory.yml

---
- name: Create AWS VPC, Subnets, and Security Groups
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Create VPC
      community.aws.ec2_vpc_net:
        name: dwVPC
        cidr_block: 10.1.0.0/16
        region: us-east-1
      register: vpc_result