# ansible-playbook deploy.yml -i group_vars/vultr.yml

-

        block:

          
          - name: Copy ssh key
            local_action: 
              module: vultr_ssh_key
              name: "{{ user }}"
              ssh_key: "{{ lookup('file', '~/.ssh/authorized_keys') }}"


          - name: Create firewallgroup
            local_action: 
              module: vultr_firewall_group
              name: "{{ firewall_group }}"


    #     - name: Get public IP of ansible host
    #       command: hostname -I
    #       register: public_ip 


          - name: Set firewall rules 
            local_action:
              module: vultr_firewall_rule
              group: "{{ firewall_group }}"
              protocol: tcp
              port: 22
              ip_version: v4
              cidr: "{{ public_ip }}/32"


          - name: Ensure VM exists
            local_action:
              module: vultr_server
              name: "{{ hostname }}"
              os: "{{ image }}"
              plan: "{{ plan }}"
              firewall_group: "{{ firewall_group }}"
              ssh_key: ansible
              region: "{{ region }}"


