# ansible-playbook deploy.yml -i group_vars/vultr.yml

-

        block:

          - name: Ensure VM exists
            local_action:
              module: vultr_server
              name: "{{ hostname }}"
              os: "{{ image }}"
              plan: "{{ plan }}"
              region: "{{ region }}"


          - name: Copy ssh key
            local_action: 
              module:
              name:
              ssh_key:
